FROM node:20
WORKDIR /app

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./
COPY libs ./libs
COPY tsconfig*.json ./
COPY apps/auth ./apps/auth

RUN npm install
RUN npm run build auth
CMD ["node", "dist/apps/auth/main.js"]