FROM node:20
WORKDIR /app

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./
COPY libs ./libs
COPY tsconfig*.json ./
COPY apps/tags-service ./apps/tags-service

RUN npm install
RUN npm run build tags-service
CMD ["node", "dist/apps/tags-service/main.js"]