FROM node:20
WORKDIR /app

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./
COPY libs ./libs
COPY tsconfig*.json ./
COPY apps/calls-service ./apps/calls-service

RUN npm install
RUN npm run build calls-service
CMD ["node", "dist/apps/calls-service/main.js"]